services:
  web:
    build:
      context: .
      dockerfile: ./deployment/dockerfiles/web/Dockerfile
      args:
        RUBY_VERSION: 3.2.2
    image: web-dev
    entrypoint: [ "bin/docker-entrypoint.sh" ]
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "127.0.0.1:${DEV_APP_PORT}:3000"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=${STG_SECRET_KEY_BASE}
      - APP_HOST=${STG_APP_HOST}
      - APP_PORT=${STG_APP_PORT}
      - DB_HOST=${STG_DB_HOST}
      - DB_PORT=${STG_DB_PORT}
      - DB_USER=${STG_DB_USER}
      - DB_PASSWORD=${STG_DB_PASSWORD}
      - SMTP_ADDRESS=${STG_SMTP_ADDRESS}
      - SMTP_PORT=${STG_SMTP_PORT}
      - SMTP_DOMAIN=${STG_SMTP_DOMAIN}
      - SMTP_USERNAME=${STG_SMTP_USERNAME}
      - SMTP_PASSWORD=${STG_SMTP_PASSWORD}
      - SMTP_SENDER_NAME=${STG_SMTP_SENDER_NAME}
      - SMTP_SENDER_EMAIL=${STG_SMTP_SENDER_EMAIL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${STG_DB_USER}
      - POSTGRES_PASSWORD=${STG_DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7.2.0
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  pg_data:
  redis_data:
  bundle:
